PROJECT: 'bitrap_np_ptitan'
CKPT_DIR: 'checkpoints/TITAN_checkpoints/'
OUT_DIR: 'outputs/TITAN_outputs/'
DEVICE: 'cuda'
METHOD: 'BiTraPNP'
VISUALIZE: True
IS_TITAN: True
MODEL:
  IMG_SIZE: (256,256)
  BEST_OF_MANY: True
  K: 20 # Set to 1 for BiTraP-D, set to 20 for BiTraP-NP
  LATENT_DIST: 'gaussian'
  LATENT_DIM: 32

  PRED_LEN: 15 # input and pred_len is defined in 30FPS
  GLOBAL_EMBED_SIZE: 256
  GLOBAL_HIDDEN_SIZE:  256
  GLOBAL_INPUT_DIM: 4
  DROPOUT: 0.0

  ENC_CONCAT_TYPE: 'average'
  INPUT_EMBED_SIZE: 256
  FLOW_EMBED_SIZE: 256
  FLOW_HIDDEN_SIZE: 256
  ENC_HIDDEN_SIZE: 256
  DEC_INPUT_SIZE: 256
  DEC_HIDDEN_SIZE: 256
  DEC_OUTPUT_DIM: 4
DATASET:
  NAME: 'TITAN'
  ROOT: /home/anbae/Documents/Research/Datasets/TITAN
  TRAJECTORY_PATH: /data_cache/
  BBOX_TYPE: 'cxcywh' # bbox is in cxcywh format
  NORMALIZE: 'zero-one'
  MIN_BBOX: [0,0,0,0] # the min of cxcywh or x1x2y1y2
  MAX_BBOX: [1920, 1200, 1920, 1200] # the max of cxcywh or x1x2y1y2 (TITAN dataset is recorded in 1920x1200 not 1920x1080)
  FPS: 10  # The TITAN dataset is recorded in 60 fps but annotations are only in 10 hz
DATALOADER:
  NUM_WORKERS: 24
SOLVER:
  MAX_EPOCH: 50
  BATCH_SIZE: 128
  LR: 0.001
  scheduler: 'plateau'
TEST:
  BATCH_SIZE: 1024